config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
]

core/urls.py
from django.urls import path
from notes import views as note_views

app_name = "core"

urlpatterns = [
    path("", note_views.HomeView.as_view(), name="home")
]

core/models.py
from django.db import models

# Create your models here.


class TimeStampedModel(models.Model):

    """ Time Stamped Model """

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

notes/models.py
from django.db import models
from core import models as core_models

# Create your models here.


class Note(core_models.TimeStampedModel):
    title = models.CharField(max_length=120)
    text = models.TextField()

core/views.py
from django.shortcuts import render

# Create your views here.

notes/views.py
from django.shortcuts import render
from django.views.generic import ListView
from . import models

# Create your views here.


class HomeView(ListView):

    """ Home View Definition """

    model = models.Note
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "notes"

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
     <title>{% block page_title %}{% endblock page_title %}ABclone</title>
  </head>
  <body class="text-gray-800 mt-24 font-light">
    <header class="container max-w-full inset-0 flex item-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white">
        <div class="flex items-center w-1/3">
          <a href="{% url "core:home" %}" class="mr-6">
            <img class="w-8" src="{% static 'img/logo.png' %}">
          </a>
 
        </div>
        {% include 'partials/nav.html' %}
    </header>

    {% block content %}
    {% endblock content %}

    {% include "partials/footer.html" %}

  </body>
</html>

templates/notes/note_list.html
{% extends 'base.html' %}

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500 flex flex-col">
   <span>{% trans "Please don't copy us" %}</span>
    
   <span>&copy; 2020 Note. {% trans 'All rights reserved.' %} </span>
   
</footer>

templates/partials/nav.html
{% load i18n %}
<ul class="flex items-center text-sm font-medium">

        <li>Home</li>
</ul>